name: Exercitium
version: 0.1.0.0
github: "jaalonso/Exercitium"
license: BSD3
author: "Jose A. Alonso"
maintainer: "JoseA.Alonso@gmail.com"
copyright: "Jose A. Alonso"
synopsis: Ejercicios de programación funcional con Haskell
description: >
  Soluciones de los ejercicios de programación funcional propuestos en el
  blog Exercitium.
category: Educational

extra-source-files:
  - README.org

dependencies:
  - base >= 4.7 && < 5
  - arithmoi
  - array
  - combinat
  - containers
  - data-memocombinators
  - data-ordlist
  - digits
  - fast-digits
  - hspec
  - hspec-core
  - integer-logarithms
  - matrix
  - mtl
  - primes
  - QuickCheck
  - quickcheck-higherorder
  - random
  - set-monad
  - split
  - statistics
  - statistics-linreg
  - vector

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-type-defaults
  dependencies:
  - base >=4.7 && <5
  - gnuplot
  - I1M

tests:
  Exercitium-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Exercitium
    - base
    - hspec
    - hspec-core
    - I1M
